version: "3"

services:
  web: &web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mergingHW:/app
    command: flask run --debugger --host=0.0.0.0
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
volumes:
  pgdata:
